In [1]:
import numpy as np
import pandas as pd

Function-1 [2-Dimensional]

In [12]:
#function1_inputs = np.load('../data/initial_data/function_1/initial_inputs.npy')
#function1_outputs = np.load('../data/initial_data/function_1/initial_outputs.npy')
function1_inputs = np.load('../data/week9/function_1/inputs.npy')
function1_outputs = np.load('../data/week9/function_1/outputs.npy')

# ==== Import New Data ====

f1_new_inputs = np.array([0.446826,0.999040])
f1_new_output = np.array([np.float64(-3.2630040678240334e-119)])


# ==== Join old and new data ====

function1_inputs_updated = np.vstack([function1_inputs, f1_new_inputs])
print(function1_inputs_updated)

function1_outputs_updated = np.concatenate((function1_outputs, f1_new_output))
print(function1_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_1/inputs', function1_inputs_updated)
np.save('../data/week10/function_1/outputs', function1_outputs_updated)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.65       0.3       ]
 [0.15       0.85      ]
 [0.85       0.15      ]
 [0.2        0.8       ]
 [0.85       0.45      ]
 [0.15       0.9       ]
 [0.05       0.95      ]
 [0.856518   0.784052  ]
 [0.446826   0.99904   ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048 -3.98693469e-048  2.85566405e-181
  2.85566405e-181  1.59622584e-134 -6.50000083e-057 -1.83222334e-211
  4.40606439e-291 -2.28824880e-053 -3.26300407e-119]


Function-2 [2-Dimensional]

In [13]:
#function2_inputs = np.load('../data/initial_data/function_2/initial_inputs.npy')
#function2_outputs = np.load('../data/initial_data/function_2/initial_outputs.npy')
function2_inputs = np.load('../data/week9/function_2/inputs.npy')
function2_outputs = np.load('../data/week9/function_2/outputs.npy')

# ==== Import New Data ====

f2_new_inputs = np.array([0.701768,0.959508])
f2_new_output = np.array([np.float64(0.5438154484996878)])


# ==== Join old and new data ====

function2_inputs_updated = np.vstack([function2_inputs, f2_new_inputs])
print(function2_inputs_updated)

function2_outputs_updated = np.concatenate((function2_outputs, f2_new_output))
print(function2_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_2/inputs', function2_inputs_updated)
np.save('../data/week10/function_2/outputs', function2_outputs_updated)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.2        0.4       ]
 [0.35       0.65      ]
 [0.4        0.7       ]
 [0.5        0.8       ]
 [0.55       0.65      ]
 [0.6        0.55      ]
 [0.65       0.45      ]
 [0.741411   0.906791  ]
 [0.741411   0.906791  ]
 [0.701768   0.959508  ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522 -0.0694397   0.09282575
  0.03634587  0.49795941  0.27219175  0.1581707   0.40371779  0.42799762
  0.42799762  0.54381545]


Function-3 [3-Dimensional]

In [14]:
#function3_inputs = np.load('../data/initial_data/function_3/initial_inputs.npy')
#function3_outputs = np.load('../data/initial_data/function_3/initial_outputs.npy')
function3_inputs = np.load('../data/week9/function_3/inputs.npy')
function3_outputs = np.load('../data/week9/function_3/outputs.npy')
# ==== Import New Data ====

f3_new_inputs = np.array([0.687434,0.363109,0.223505])
f3_new_output = np.array([np.float64(-0.12598852455903542)])


# ==== Join old and new data ====

function3_inputs_updated = np.vstack([function3_inputs, f3_new_inputs])
print(function3_inputs_updated)

function3_outputs_updated = np.concatenate((function3_outputs, f3_new_output))
print(function3_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_3/inputs', function3_inputs_updated)
np.save('../data/week10/function_3/outputs', function3_outputs_updated)

[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.7        0.25       0.6       ]
 [0.72       0.32       0.55      ]
 [0.74       0.3        0.58      ]
 [0.3        0.7        0.4       ]
 [0.2        0.8        0.3       ]
 [0.85       0.2        0.7       ]
 [0.9        0.1        0.6       ]
 [0.618994   0.670063   0.016173  ]
 [0.687434   0.363109   0.223505  ]]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -

In [ ]:
Function-4 [4-Dimensional]

In [15]:
#function4_inputs = np.load('../data/initial_data/function_4/initial_inputs.npy')
#function4_outputs = np.load('../data/initial_data/function_4/initial_outputs.npy')
function4_inputs = np.load('../data/week9/function_4/inputs.npy')
function4_outputs = np.load('../data/week9/function_4/outputs.npy')

# ==== Import New Data ====

f4_new_inputs = np.array([0.377638,0.420999,0.443845,0.335037])
f4_new_output = np.array([np.float64(0.07786151133373709)])


# ==== Join old and new data ====

function4_inputs_updated = np.vstack([function4_inputs, f4_new_inputs])
print(function4_inputs_updated)

function4_outputs_updated = np.concatenate((function4_outputs, f4_new_output))
print(function4_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_4/inputs', function4_inputs_updated)
np.save('../data/week10/function_4/outputs', function4_outputs_updated)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

Function-5 [4-Dimensional]

In [16]:
#function5_inputs = np.load('../data/initial_data/function_5/initial_inputs.npy')
#function5_outputs = np.load('../data/initial_data/function_5/initial_outputs.npy')
function5_inputs = np.load('../data/week9/function_5/inputs.npy')
function5_outputs = np.load('../data/week9/function_5/outputs.npy')

# ==== Import New Data ====

f5_new_inputs = np.array([0.682235,0.890909,0.996925,0.956954])
f5_new_output = np.array([np.float64(3407.1676989161297)])


# ==== Join old and new data ====

function5_inputs_updated = np.vstack([function5_inputs, f5_new_inputs])
print(function5_inputs_updated)

function5_outputs_updated = np.concatenate((function5_outputs, f5_new_output))
print(function5_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_5/inputs', function5_inputs_updated)
np.save('../data/week10/function_5/outputs', function5_outputs_updated)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.81       0.6        0.2        0.412     ]
 [0.8        

Function-6 [5-Dimensional]

In [17]:
#function6_inputs = np.load('../data/initial_data/function_6/initial_inputs.npy')
#function6_outputs = np.load('../data/initial_data/function_6/initial_outputs.npy')
function6_inputs = np.load('../data/week9/function_6/inputs.npy')
function6_outputs = np.load('../data/week9/function_6/outputs.npy')

# ==== Import New Data ====

f6_new_inputs = np.array([0.296253,0.146042,0.756481,0.592836,0.002754])
f6_new_output = np.array([np.float64(-0.6894510077091464)])


# ==== Join old and new data ====

function6_inputs_updated = np.vstack([function6_inputs, f6_new_inputs])
print(function6_inputs_updated)

function6_outputs_updated = np.concatenate((function6_outputs, f6_new_output))
print(function6_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_6/inputs', function6_inputs_updated)
np.save('../data/week10/function_6/outputs', function6_outputs_updated)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

Function-7 [6-Dimensional]

In [18]:
#function7_inputs = np.load('../data/initial_data/function_7/initial_inputs.npy')
#function7_outputs = np.load('../data/initial_data/function_7/initial_outputs.npy')
function7_inputs = np.load('../data/week9/function_7/inputs.npy')
function7_outputs = np.load('../data/week9/function_7/outputs.npy')

# ==== Import New Data ====

f7_new_inputs = np.array([0.036236,0.385959,0.271302,0.111172,0.275532,0.707476])
f7_new_output = np.array([np.float64(1.6305972297527618)])


# ==== Join old and new data ====

function7_inputs_updated = np.vstack([function7_inputs, f7_new_inputs])
print(function7_inputs_updated)

function7_outputs_updated = np.concatenate((function7_outputs, f7_new_output))
print(function7_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_7/inputs', function7_inputs_updated)
np.save('../data/week10/function_7/outputs', function7_outputs_updated)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

Function-8 [8-Dimensional]

In [19]:
#function8_inputs = np.load('../data/initial_data/function_8/initial_inputs.npy')
#function8_outputs = np.load('../data/initial_data/function_8/initial_outputs.npy')
function8_inputs = np.load('../data/week9/function_8/inputs.npy')
function8_outputs = np.load('../data/week9/function_8/outputs.npy')

# ==== Import New Data ====

f8_new_inputs = np.array([0.055632,0.111569,0.285940,0.087775,0.942216,0.677759,0.227712,0.850754])
f8_new_output = np.array([np.float64(9.8682275938174)])


# ==== Join old and new data ====

function8_inputs_updated = np.vstack([function8_inputs, f8_new_inputs])
print(function8_inputs_updated)

function8_outputs_updated = np.concatenate((function8_outputs, f8_new_output))
print(function8_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save('../data/week10/function_8/inputs', function8_inputs_updated)
np.save('../data/week10/function_8/outputs', function8_outputs_updated)

[[0.60499445 0.29221502 0.90845275 0.35550624 0.20166872 0.57533801
  0.31031095 0.73428138]
 [0.17800696 0.56622265 0.99486184 0.21032501 0.32015266 0.70790879
  0.63538449 0.10713163]
 [0.00907698 0.81162615 0.52052036 0.07568668 0.26511183 0.09165169
  0.59241515 0.36732026]
 [0.50602816 0.65373012 0.36341078 0.17798105 0.0937283  0.19742533
  0.7558269  0.29247234]
 [0.35990926 0.24907568 0.49599717 0.70921498 0.11498719 0.28920692
  0.55729515 0.59388173]
 [0.77881834 0.0034195  0.33798313 0.51952778 0.82090699 0.53724669
  0.5513471  0.66003209]
 [0.90864932 0.0622497  0.23825955 0.76660355 0.13233596 0.99024381
  0.68806782 0.74249594]
 [0.58637144 0.88073573 0.74502075 0.54603485 0.00964888 0.74899176
  0.23090707 0.09791562]
 [0.76113733 0.85467239 0.38212433 0.33735198 0.68970832 0.30985305
  0.63137968 0.04195607]
 [0.9849332  0.69950626 0.9988855  0.18014846 0.58014315 0.23108719
  0.49082694 0.31368272]
 [0.11207131 0.43773566 0.59659878 0.59277563 0.22698177 0.41010452
  